### ISSUE TITLE
Include date and username in provenance metadata?

### ISSUE THREAD

**Issue by aekiss** [COSIMA/om3-scripts#14]
Generation date and username can be very useful for knowing which versions of a file are more up to date and  knowing who to ask about it. Could these be added to `get_provenance_metadata`?

(I know date is somewhat redundant since it's sort-of implicit in the git hash, but it's nicer to have something more direct.)

**Comment by anton-seaice** [comment]
In `generate_mesh.py` these are added as seperate attributes to the netcdf file.

https://github.com/COSIMA/om3-scripts/blob/349a583786e200991c22649a2757a426b4e67948/mesh_generation/generate_mesh.py#L166-L170

However this approach is not very extensible to writing in xml (for the data_stream generation) or into the single description field for an intake datastore.

Because python is not typed!, we could have a flag for the type of the output from `get_provenance_metdata` to produce a dict for netcdf files, but other wise produce a single string ?

(Or we could make life simple and just put all the information in a single string always).

The single string would be like:

`
"Created by as2285, on 2024-07-18, using https://github.com/COSIMA/om3-scripts/blob/349a583786e200991c22649a2757a426b4e67948/mesh_generation/generate_mesh.py: python3 generate_mesh.py --grid-type=mom --grid-filename=/g/data/ik11/inputs/access-om2/input_20230515_025deg_topog/mom_025deg/ocean_hgrid.nc --mesh-filename=/g/data/tm70/as2285/om3-scripts/test.nc" ;
`
